### ISSUE TITLE
ocrodjvu for tesseract  3.04.00

### ISSUE THREAD

**Issue by jwilk** [jwilk/ocrodjvu#14]
**Issue reported by @jsbien**:

Tesseract 3.04.00 allows a new parameter: hocr_font_info. I think it should be switched on.

I've patched ocrodjvu and made a simple test. It seems to work OK, but I get the message "Warning in pixReadMemTiff: tiff page 1 not found" twice for every processed page. 

The explanation provided on the list

https://groups.google.com/forum/#!topic/tesseract-ocr/Yl58Bn0N168

doesn't seem relevant for this case.

**Comment by jsbien** [comment]
I think it's time to close this issue, my problem is better solved by issue #26. On the other hand, Tesseract is now at version 4.0...

**Comment by jwilk** [comment]
Agreed; let's close it.
