### ISSUE TITLE
quneiform support

### ISSUE THREAD

**Issue by jwilk** [jwilk/ocrodjvu#24]
Long time ago, @LazyKent requested adding support for [quneiform](https://github.com/uliss/quneiform).

Let's track this feature request here.

**Comment by LazyKent** [comment]
It seems, support for quneiform is useless.

The latest commit to quneiform is dated Dec 2, 2012.
The project is dead  (and [cuneiform](https://launchpad.net/cuneiform-linux/+announcement/8374) itself is dead as well).

**Comment by jwilk** [comment]
OK, let's close this.
