### ISSUE TITLE
Conversion of hocr to djvused as a separate utility

### ISSUE THREAD

**Issue by jsbien** [jwilk/ocrodjvu#27]
This is actually renamed the main aspect of issue #19.

**Comment by jwilk** [comment]
But [hocr2djvused](https://manpages.debian.org/unstable/ocrodjvu/hocr2djvused.1) already exists…

**Comment by jsbien** [comment]
Yes of course. Looks like  I misunderstand my own issue #19, perhaps at that time there was no way to save hOCR files and this was what I had in mind? A stupid mistake of mine :-( Of course the issue is to be closed.

BTW, some hOCR utilities t available at present only at https://bitbucket.org/jwilk/marasca-wbl/src/wbl/misc/xhocr/ deserve perhaps more publicity as they are not marasca specific.

**Comment by jwilk** [comment]
> course the issue is to be closed

OK, closing it now.

I've filed separate issue for maraca hOCR utilities.
