### ISSUE TITLE
Tesseract 4: error: invalid language identifier: Latin

### ISSUE THREAD

**Issue by vltavskachobotnice** [jwilk/ocrodjvu#29]
For example from https://github.com/tesseract-ocr/tessdata/tree/master/script. Now ocrodjvu returns this error:

 ./ocrodjvu --in-place -l Latin foo.djvu 
usage: ocrodjvu [options] FILE
ocrodjvu: error: invalid language identifier: Latin; language identifier is typically an ISO 639-2 three-letter code

**Comment by jwilk** [comment]
Thanks for the bug report, and sorry for dropping ball on this. It will be fixed in the next version, which I hope to release in a few days.

**Comment by jwilk** [comment]
Fixed in 0.11.
