### ISSUE TITLE
allow passing arbitrary options to Tesseract

### ISSUE THREAD

**Issue by jsbien** [jwilk/ocrodjvu#30]
From https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage:
Use --oem 1 for LSTM, --oem 0 for Legacy Tesseract

Actually any way to pass parameters directly to tesseract would solve this and the previous issue.

**Comment by jwilk** [comment]
In 0.11 you can use:
```
-X extra_args='--oem 0'
```
